install:
  - pip install psycopg2
  - git submodule init
  - git submodule update
before_script:
  psql -c 'CREATE DATABASE json_test;' -U postgres
env:
  - DATABASE_URL=postgres:///json_test
services:
  - postgresql
addons:
  postgresql: "9.4"
script: python test.py
language: python
